version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: mysql-local
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: go_esb
    ports:
      - "3307:3306"
    volumes:
      - mysql_data_local:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-psecret"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-esb-test
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=mysql://root:secret@tcp(db:3306)/go_esb
    volumes:
      - ./config.json:/app/config.json

volumes:
  mysql_data_local:
